apiVersion: v2
appVersion: "5.1.8"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
deprecated: true
description: Usenet meta search
home: https://truecharts.org/charts/stable/nzbhydra
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nzbhydra.png
keywords:
  - nzbhydra
  - usenet
kubeVersion: ">=1.16.0-0"
maintainers: []
name: nzbhydra
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/nzbhydra
  - https://github.com/theotherp/nzbhydra2
type: application
version: 13.0.8
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
